In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/'
data = 'iris.data'

dfs = pd.read_table(path + data, sep=',', header=None)

In [18]:
dfs.loc[(dfs[4]=='Iris-setosa'), 4] = 0
dfs.loc[(dfs[4]=='Iris-versicolor'), 4] = 1
dfs.loc[(dfs[4]=='Iris-virginica'), 4] = 2

In [20]:
df_array = dfs.values

In [22]:
np.random.choice(150,30)

array([ 66, 138, 132,  65,  88,  92,   1,  83, 124,  45,  16, 110, 119,
        43, 145,  28,  27,  49,  74,  61, 144,  65,  54, 126, 108,  23,
         8, 106,  15,  65])

In [49]:
e = dfs.loc[np.random.choice(150, 30), :]
e.drop([4], axis=1)

0    1    2    3
18   5.7  3.8  1.7  0.3
143  6.8  3.2  5.9  2.3
91   6.1  3.0  4.6  1.4
82   5.8  2.7  3.9  1.2
32   5.2  4.1  1.5  0.1
107  7.3  2.9  6.3  1.8
26   5.0  3.4  1.6  0.4
28   5.2  3.4  1.4  0.2
29   4.7  3.2  1.6  0.2
44   5.1  3.8  1.9  0.4
11   4.8  3.4  1.6  0.2
9    4.9  3.1  1.5  0.1
54   6.5  2.8  4.6  1.5
56   6.3  3.3  4.7  1.6
103  6.3  2.9  5.6  1.8
63   6.1  2.9  4.7  1.4
19   5.1  3.8  1.5  0.3
119  6.0  2.2  5.0  1.5
46   5.1  3.8  1.6  0.2
70   5.9  3.2  4.8  1.8
89   5.5  2.5  4.0  1.3
10   5.4  3.7  1.5  0.2
123  6.3  2.7  4.9  1.8
130  7.4  2.8  6.1  1.9
98   5.1  2.5  3.0  1.1
103  6.3  2.9  5.6  1.8
145  6.7  3.0  5.2  2.3
116  6.5  3.0  5.5  1.8
88   5.6  3.0  4.1  1.3
3    4.6  3.1  1.5  0.2

In [31]:
l = list(dfs.index)

In [42]:
p = np.random.choice(l, 30)

In [47]:
notd = np.array([x for x in dfs.index if x not in p])

In [48]:
notd

array([  0,   2,   3,   6,   9,  10,  11,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
        32,  33,  34,  35,  36,  38,  39,  41,  42,  43,  45,  46,  47,
        48,  49,  50,  51,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        63,  64,  65,  66,  68,  69,  70,  72,  74,  75,  76,  78,  79,
        80,  81,  82,  84,  85,  86,  87,  88,  91,  92,  93,  94,  95,
        96,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
       111, 113, 114, 115, 116, 117, 118, 120, 121, 122, 123, 125, 126,
       127, 128, 129, 130, 132, 133, 135, 136, 138, 139, 140, 141, 143,
       145, 146, 147, 148, 149])

In [44]:
notd

[0,
 2,
 3,
 6,
 9,
 10,
 11,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 41,
 42,
 43,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 68,
 69,
 70,
 72,
 74,
 75,
 76,
 78,
 79,
 80,
 81,
 82,
 84,
 85,
 86,
 87,
 88,
 91,
 92,
 93,
 94,
 95,
 96,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 113,
 114,
 115,
 116,
 117,
 118,
 120,
 121,
 122,
 123,
 125,
 126,
 127,
 128,
 129,
 130,
 132,
 133,
 135,
 136,
 138,
 139,
 140,
 141,
 143,
 145,
 146,
 147,
 148,
 149]

In [46]:
dfs.shape[0]

150

In [50]:
np.pi * 5.1 * 5.1 / 4

20.428206229967625

In [51]:
32 / 4.35

7.356321839080461

In [52]:
15 * 7.356 / 12

9.195

In [54]:
9.155 / 2.0428 * 10**5

448159.38907382014

In [55]:
2000 / 1024

1.953125

In [58]:
A = np.pi * 5.1 * 5.1 / 4 * 10**(-6)
power_volt = 32 #[V]
energy = power_volt / 4.35 #[J]
power = 5 * 7.356 / 12
intensity = power / A * 10**(-3)
intensity

150.03764723618897

In [60]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [62]:
np.where(a == 9)

(array([], dtype=int64),)

In [73]:
a = np.array([[1,2,3],[2,3,4]])

In [75]:
a.mean(axis=0)

array([1.5, 2.5, 3.5])